//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W9xNET.User32.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ActiveTitleBar_ItemSize {
            get {
                return ((int)(this["ActiveTitleBar_ItemSize"]));
            }
            set {
                this["ActiveTitleBar_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color ActiveTitleBar_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["ActiveTitleBar_ItemColor"]));
            }
            set {
                this["ActiveTitleBar_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt, style=Bold")]
        public global::System.Drawing.Font ActiveTitleBar_Font {
            get {
                return ((global::System.Drawing.Font)(this["ActiveTitleBar_Font"]));
            }
            set {
                this["ActiveTitleBar_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ActiveWindowBorder_ItemSize {
            get {
                return ((int)(this["ActiveWindowBorder_ItemSize"]));
            }
            set {
                this["ActiveWindowBorder_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ActiveWindowBorder_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["ActiveWindowBorder_ItemColor"]));
            }
            set {
                this["ActiveWindowBorder_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ApplicationBackground_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["ApplicationBackground_ItemColor"]));
            }
            set {
                this["ApplicationBackground_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int CaptionButtons_ItemSize {
            get {
                return ((int)(this["CaptionButtons_ItemSize"]));
            }
            set {
                this["CaptionButtons_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color Desktop_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["Desktop_ItemColor"]));
            }
            set {
                this["Desktop_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 32")]
        public global::System.Drawing.Size Icon_ItemSize {
            get {
                return ((global::System.Drawing.Size)(this["Icon_ItemSize"]));
            }
            set {
                this["Icon_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt")]
        public global::System.Drawing.Font Icon_Font {
            get {
                return ((global::System.Drawing.Font)(this["Icon_Font"]));
            }
            set {
                this["Icon_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public int IconSpacingHorizontal_ItemSize {
            get {
                return ((int)(this["IconSpacingHorizontal_ItemSize"]));
            }
            set {
                this["IconSpacingHorizontal_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public int IconSpacingVertical_ItemSize {
            get {
                return ((int)(this["IconSpacingVertical_ItemSize"]));
            }
            set {
                this["IconSpacingVertical_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int InactiveTitleBar_ItemSize {
            get {
                return ((int)(this["InactiveTitleBar_ItemSize"]));
            }
            set {
                this["InactiveTitleBar_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color InactiveTitleBar_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["InactiveTitleBar_ItemColor"]));
            }
            set {
                this["InactiveTitleBar_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt, style=Bold")]
        public global::System.Drawing.Font InactiveTitleBar_Font {
            get {
                return ((global::System.Drawing.Font)(this["InactiveTitleBar_Font"]));
            }
            set {
                this["InactiveTitleBar_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color InactiveTitleBar_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["InactiveTitleBar_FontColor"]));
            }
            set {
                this["InactiveTitleBar_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InactiveWindowBorder_ItemSize {
            get {
                return ((int)(this["InactiveWindowBorder_ItemSize"]));
            }
            set {
                this["InactiveWindowBorder_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color InactiveWindowBorder_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["InactiveWindowBorder_ItemColor"]));
            }
            set {
                this["InactiveWindowBorder_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int Menu_ItemSize {
            get {
                return ((int)(this["Menu_ItemSize"]));
            }
            set {
                this["Menu_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color Menu_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["Menu_ItemColor"]));
            }
            set {
                this["Menu_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt")]
        public global::System.Drawing.Font Menu_Font {
            get {
                return ((global::System.Drawing.Font)(this["Menu_Font"]));
            }
            set {
                this["Menu_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Menu_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["Menu_FontColor"]));
            }
            set {
                this["Menu_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt")]
        public global::System.Drawing.Font MessageBox_Font {
            get {
                return ((global::System.Drawing.Font)(this["MessageBox_Font"]));
            }
            set {
                this["MessageBox_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MessageBox_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["MessageBox_FontColor"]));
            }
            set {
                this["MessageBox_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PaletteTitle_ItemSize {
            get {
                return ((int)(this["PaletteTitle_ItemSize"]));
            }
            set {
                this["PaletteTitle_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt")]
        public global::System.Drawing.Font PaletteTitle_Font {
            get {
                return ((global::System.Drawing.Font)(this["PaletteTitle_Font"]));
            }
            set {
                this["PaletteTitle_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ScrollBar_ItemSize {
            get {
                return ((int)(this["ScrollBar_ItemSize"]));
            }
            set {
                this["ScrollBar_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int SelectedItems_ItemSize {
            get {
                return ((int)(this["SelectedItems_ItemSize"]));
            }
            set {
                this["SelectedItems_ItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color SelectedItems_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedItems_ItemColor"]));
            }
            set {
                this["SelectedItems_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SelectedItems_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedItems_FontColor"]));
            }
            set {
                this["SelectedItems_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt")]
        public global::System.Drawing.Font SelectedItems_Font {
            get {
                return ((global::System.Drawing.Font)(this["SelectedItems_Font"]));
            }
            set {
                this["SelectedItems_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 225")]
        public global::System.Drawing.Color ToolTip_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["ToolTip_ItemColor"]));
            }
            set {
                this["ToolTip_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ToolTip_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["ToolTip_FontColor"]));
            }
            set {
                this["ToolTip_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8pt")]
        public global::System.Drawing.Font ToolTip_Font {
            get {
                return ((global::System.Drawing.Font)(this["ToolTip_Font"]));
            }
            set {
                this["ToolTip_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ThreeDObjects_ItemColor {
            get {
                return ((global::System.Drawing.Color)(this["ThreeDObjects_ItemColor"]));
            }
            set {
                this["ThreeDObjects_ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ThreeDObjects_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["ThreeDObjects_FontColor"]));
            }
            set {
                this["ThreeDObjects_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsClearType {
            get {
                return ((bool)(this["IsClearType"]));
            }
            set {
                this["IsClearType"] = value;
            }
        }
    }
}
