//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalMitigation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegalMitigation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9xNET - Development Build.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert CD-ROM.
        /// </summary>
        public static string InsertCdRom {
            get {
                return ResourceManager.GetString("InsertCdRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert DVD-ROM.
        /// </summary>
        public static string InsertDvdRom {
            get {
                return ResourceManager.GetString("InsertDvdRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert your Microsoft® Windows® 95 CD-ROM to continue..
        /// </summary>
        public static string PleaseInsertYourWindows95CdRomToContinue {
            get {
                return ResourceManager.GetString("PleaseInsertYourWindows95CdRomToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert your Microsoft® Windows® 98 CD-ROM to continue..
        /// </summary>
        public static string PleaseInsertYourWindows98CdRomToContinue {
            get {
                return ResourceManager.GetString("PleaseInsertYourWindows98CdRomToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert your Microsoft® Windows® 98 Second Edition CD-ROM to continue..
        /// </summary>
        public static string PleaseInsertYourWindows98SeCdRomToContinue {
            get {
                return ResourceManager.GetString("PleaseInsertYourWindows98SeCdRomToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert your Microsoft® Windows® Millennium Edition CD-ROM to continue..
        /// </summary>
        public static string PleaseInsertYourWindowsMeCdRomToContinue {
            get {
                return ResourceManager.GetString("PleaseInsertYourWindowsMeCdRomToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Setup.
        /// </summary>
        public static string ProductSetup {
            get {
                return ResourceManager.GetString("ProductSetup", resourceCulture);
            }
        }
    }
}
